provider:
  base_url: "https://dashscope-intl.aliyuncs.com/compatible-mode/v1"
  model: "qwen2.5-vl-72b-instruct"
  api_key_env: "DASHSCOPE_API_KEY"
  request_timeout_s: 120
  max_retries: 2
  temperature: 0.0
  top_p: 0.1
inference:
  max_items: 50
  conf_threshold: 0.20
  iou_merge_threshold: 0.0
dataset:
  input_dir: "test_images"
  out_json_dir: "outputs/json"
  out_viz_dir: "outputs/viz"